name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read


jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - { os: ubuntu-24.04, ruby: "2.0.0" }
          - { os: ubuntu-24.04, ruby: 2.1 }
          - { os: ubuntu-24.04, ruby: 2.3 }
          - { os: ubuntu-24.04, ruby: 2.4 }
          - { os: ubuntu-24.04, ruby: 2.5 }
          - { os: ubuntu-24.04, ruby: 2.6 }
          - { os: ubuntu-24.04, ruby: 2.7 }
          - { os: ubuntu-24.04, ruby: "3.0" }
          - { os: ubuntu-24.04, ruby: 3.1 }
          - { os: ubuntu-26.04, ruby: 3.2 }
          - { os: ubuntu-26.04, ruby: 3.3 }
          - { os: ubuntu-26.04, ruby: 3.4 }
          - { os: ubuntu-26.04, ruby: "4.0" }
          - { os: ubuntu-26.04, ruby: jruby-10.0 }
          - { os: ubuntu-26.04, ruby: jruby-10.1 }
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.ruby }}
    env:
      BUNDLE_GEMFILE: .ci.gemfile
      COFFEE_SCRIPT: use
    steps:
    - uses: actions/checkout@v6
    # Pandoc needs Pandoc
    - run: sudo apt-get install -y pandoc
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
        cache-version: 1
    - run: bundle exec rake
